---
name: "Tools - Validate Dockerfile Schema"

"on":
  pull_request:
    branches:
      - "master"
    paths:
      - "**Dockerfile"

permissions:
  contents: read

jobs:
  validate-dockerfile-schema:
    name: Haskell Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Validate Dockerfile files
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5  # v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true
          ignore: "DL3008,DL3015,DL3018"