---
name: Tools - Docker Build Test

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - '**Dockerfile'

permissions:
  contents: read

env:
  REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}

jobs:
  docker-build-image:
    name: Docker Build Image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dockerfile: [ipref3, nginx, php-fpm]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build docker images
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          file: ./docker/${{ matrix.dockerfile }}/Dockerfile
          platforms: ${{ env.REGISTRY_PLATFORMS }}