---
name: "Tools - Validate YAML Schema"

"on":
  pull_request:
    branches:
      - "master"
    paths:
      - ".yamllint"
      - "**.yaml"
      - "**.yml"
      - "**.yml.example"

permissions:
  contents: read

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Validate YAML files
        run: yamllint .
